service: lambda-service-github
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
